"""users table

Revision ID: 733b8a57a65f
Revises: f9b17074c5fa
Create Date: 2020-04-15 05:10:29.688672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733b8a57a65f'
down_revision = 'f9b17074c5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_column('user', 'timestamp')
    # ### end Alembic commands ###
