"""empty message

Revision ID: f9b17074c5fa
Revises: 
Create Date: 2020-04-15 04:30:16.199871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b17074c5fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('eFirst', sa.String(length=64), nullable=True),
    sa.Column('eLast', sa.String(length=64), nullable=True),
    sa.Column('jFirst', sa.String(length=64), nullable=True),
    sa.Column('jLast', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_eFirst'), 'user', ['eFirst'], unique=False)
    op.create_index(op.f('ix_user_eLast'), 'user', ['eLast'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_jFirst'), 'user', ['jFirst'], unique=False)
    op.create_index(op.f('ix_user_jLast'), 'user', ['jLast'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_jLast'), table_name='user')
    op.drop_index(op.f('ix_user_jFirst'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_eLast'), table_name='user')
    op.drop_index(op.f('ix_user_eFirst'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
